using Content.AL.UIKit;
using Content.Shared.Chemistry;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Chemistry.UI;

[GenerateTypedNameReferences]
public sealed partial class ReagentCardControl : Control
{
    public string StorageSlotId { get; }
    public Action<string>? OnPressed;
    public Action<string>? OnEjectButtonPressed;

    public ReagentCardControl(ReagentInventoryItem item)
    {
        RobustXamlLoader.Load(this);

        StorageSlotId = item.StorageSlotId;
        // This is kind of terrible to hardcode in here.
        ColorPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = item.ReagentColor with { A = 1f } }.Extrude(new(0, 5));
        ReagentNameLabel.Text = item.ReagentLabel;
        FillLabel.Text = item.StoredAmount;
        EjectButton.Text = Loc.GetString("reagent-dispenser-window-eject-container-button");

        MainButton.OnPressed += args => OnPressed?.Invoke(StorageSlotId);
        EjectButton.OnPressed += args => OnEjectButtonPressed?.Invoke(StorageSlotId);
    }
}
