using Content.Client._AL.UI.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class EscapeMenu : Window
    {
        public EscapeMenu()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
