using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.ALED.Screen;

[GenerateTypedNameReferences]
public sealed partial class EditorScreen : UIScreen
{
    public EditorScreen()
    {
        RobustXamlLoader.Load(this);

        SetAnchorPreset(Container, LayoutPreset.Wide);
    }
}
