using System.Linq;
using Content.Client._AL.UI.Interfaces;
using Content.Client._AL.UI.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._AL.UI.Windows.OptionsMenu;

[GenerateTypedNameReferences]
public sealed partial class OptionsMenuWindow : Window, IApplyableDialog
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public OptionsMenuWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public event Action? OnModified;

    public void Modified(Control control)
    {
        // wink wonk
        OnModified?.Invoke();
    }

    public void Apply()
    {
        UiTab.Apply();
        _cfg.SaveToFile();
    }
}
