using System.Linq;
using Content.Client._AL.UI.Interfaces;
using Content.Client._AL.UI.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._AL.UI.Windows.OptionsMenu;

[GenerateTypedNameReferences]
public sealed partial class OptionsMenuWindow : Window, IApplyableDialog
{
    public OptionsMenuWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public event Action? OnModified;

    public void RegisterOption(IDialogOption option)
    {
        option.OnModified += () =>
        {
            OnModified?.Invoke();
        };
    }

    public void Apply()
    {
        throw new NotImplementedException();
    }
}
