// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.

using Content.Client._AL.UI.Widgets;
using Robust.Client.AutoGenerated;

namespace Content.Client._AL.UI.Windows.OptionsMenu.Tabs;

[GenerateTypedNameReferences]
public sealed partial class ALAudioTab : VGrowStack
{
}
