using Content.Client._AL.UI.Widgets;
using Robust.Client.AutoGenerated;

namespace Content.Client._AL.UI.Windows.OptionsMenu.Tabs;

[GenerateTypedNameReferences]
public sealed partial class ALCreditsTab : VGrowStack
{
}
